version: '3'
services:
  deploy:
    container_name: deploy
    image: hashicorp/terraform:1.2.6
    env_file:
      - .env
    volumes:
      - .:/code
    working_dir: /code/terraform
    entrypoint: ash
    tty: true
